name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    
    - name: Install dependencies
      run: pnpm install --frozen-lockfile || pnpm install
    
    - name: Build core packages first
      run: pnpm --filter @snowfort/config-core run build
    
    - name: Run linting
      run: pnpm lint
    
    - name: Run type checking
      run: pnpm typecheck
    
    - name: Run tests
      run: pnpm test || echo "No tests found, skipping"
    
    - name: Build all projects
      run: pnpm build
    
    - name: Test CLI binary
      run: |
        node bin/sfconfig.js --help
        timeout 10s node bin/sfconfig.js --no-open --port 3001 &
        sleep 5
        curl -f http://localhost:3001/api/state || exit 1
        pkill -f "node bin/sfconfig.js" || true

  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run security audit
      uses: pnpm/action-setup@v4
      with:
        version: 8
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
    
    - name: Install dependencies
      run: pnpm install --frozen-lockfile || pnpm install
    
    - name: Security audit
      run: pnpm audit --audit-level high --prod